const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const ROOT=__dirname,PORT=Number(process.env.PORT||5173),VERSION='58.0.0-review',mem=new Map(),inflight=new Map(),CACHE_DIR=path.join(ROOT,'.cache','terrain');
fs.mkdirSync(CACHE_DIR,{recursive:true});
const NDBC=['44065','44091','44025'];
const BATHY={id:'NOAA NCEI DEM Global Mosaic',service:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer',samples:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer/getSamples',export:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer/exportImage'};
function sec(type='application/json'){return {'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'geolocation=(), microphone=(), camera=()','Cross-Origin-Resource-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' https://unpkg.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"}}
function send(res,s,b,t='application/json',extra={}){res.writeHead(s,{...sec(t),...extra});res.end(b)}
function upstream(url,timeout=12000){return new Promise((resolve,reject)=>{const req=https.get(url,{timeout,headers:{'User-Agent':`BREAKSTATE-NJ/${VERSION}`,'Accept':'*/*'}},r=>{if(r.statusCode!==200){r.resume();return reject(Error(`upstream HTTP ${r.statusCode}`))}const chunks=[];let size=0;r.on('data',x=>{size+=x.length;if(size>12e6)return req.destroy(Error('upstream response too large'));chunks.push(x)});r.on('end',()=>resolve(Buffer.concat(chunks)))});req.on('timeout',()=>req.destroy(Error('upstream timeout')));req.on('error',reject)})}
async function cachedText(url,ttl=120000){const c=mem.get(url);if(c&&Date.now()-c.t<ttl)return c.v;const v=(await upstream(url)).toString('utf8');mem.set(url,{t:Date.now(),v});return v}
function num(v){v=parseFloat(v);return Number.isFinite(v)&&Math.abs(v)<10000?v:null}
function obsTime(o){const a=[o.YY,o.MM,o.DD,o.hh,o.mm||0].map(Number);return a.every(Number.isFinite)?new Date(Date.UTC(a[0],a[1]-1,a[2],a[3],a[4])).toISOString():null}
function parseNdbc(txt){const ls=txt.trim().split(/\r?\n/),h=ls[0].replace(/^#/,'').trim().split(/\s+/);for(const row of ls.slice(2)){if(!row.trim()||row.startsWith('#'))continue;const v=row.trim().split(/\s+/),o={};h.forEach((k,i)=>o[k]=v[i]);const observedAt=obsTime(o);if(observedAt)return {observedAt,waveHeightM:num(o.WVHT),periodS:num(o.DPD),waveDir:num(o.MWD),windDir:num(o.WDIR),windMS:num(o.WSPD)}}throw Error('no valid observation')}
function ageMinutes(iso){const t=Date.parse(iso);return Number.isFinite(t)?Math.max(0,Math.round((Date.now()-t)/60000)):null}
async function conditions(){const settled=await Promise.allSettled(NDBC.map(async station=>{const m=parseNdbc(await cachedText(`https://www.ndbc.noaa.gov/data/realtime2/${station}.txt`,120000));const age=ageMinutes(m.observedAt);return {station,...m,ageMinutes:age,fresh:age!==null&&age<=180}}));return {generatedAt:new Date().toISOString(),classification:'LIVE OBSERVATIONS',freshnessRuleMinutes:180,buoys:settled.filter(x=>x.status==='fulfilled').map(x=>x.value),failures:settled.filter(x=>x.status==='rejected').length}}
function tileBounds(z,x,y){const n=2**z,west=x/n*360-180,east=(x+1)/n*360-180,north=Math.atan(Math.sinh(Math.PI*(1-2*y/n)))*180/Math.PI,south=Math.atan(Math.sinh(Math.PI*(1-2*(y+1)/n)))*180/Math.PI;return {north,south,west,east}}
function tilePath(z,x,y){return path.join(CACHE_DIR,String(z),String(x),`${y}.png`)}
function validPng(buf){return Buffer.isBuffer(buf)&&buf.length>1000&&buf[0]===0x89&&buf[1]===0x50&&buf[2]===0x4e&&buf[3]===0x47}
async function buildTile(z,x,y){const file=tilePath(z,x,y);if(fs.existsSync(file)){const b=fs.readFileSync(file);if(validPng(b))return {buf:b,cache:'DISK'}}const key=`${z}/${x}/${y}`;if(inflight.has(key))return {buf:await inflight.get(key),cache:'COALESCED'};const task=(async()=>{const b=tileBounds(z,x,y),q=new URLSearchParams({bbox:`${b.west},${b.south},${b.east},${b.north}`,bboxSR:'4326',imageSR:'4326',size:'256,256',format:'png32',transparent:'false',interpolation:'RSP_BilinearInterpolation',renderingRule:JSON.stringify({rasterFunction:'ColorHillshade2'}),f:'image'}),buf=await upstream(BATHY.export+'?'+q,12000);if(!validPng(buf))throw Error('invalid terrain image');fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.tmp';fs.writeFileSync(tmp,buf);fs.renameSync(tmp,file);return buf})();inflight.set(key,task);try{return {buf:await task,cache:'MISS'}}finally{inflight.delete(key)}}
async function terrainTile(res,u){const m=u.pathname.match(/^\/api\/terrain\/(\d+)\/(\d+)\/(\d+)\.png$/);if(!m)return send(res,400,'bad tile','text/plain');const z=Number(m[1]),x=Number(m[2]),y=Number(m[3]);if(![z,x,y].every(Number.isInteger)||z<8||z>17||x<0||y<0)return send(res,400,'bad tile','text/plain');const b=tileBounds(z,x,y);if(b.north<38.7||b.south>40.8||b.east<-75.4||b.west>-73.3)return send(res,204,'','image/png',{'Cache-Control':'public, max-age=86400'});const out=await buildTile(z,x,y);send(res,200,out.buf,'image/png',{'Cache-Control':'public, max-age=31536000, immutable','X-Breakstate-Cache':out.cache,'X-Breakstate-Layer':'STATIC_BASELINE','X-Breakstate-Render':'ColorHillshade2'})}
async function identify(u){const lat=Number(u.searchParams.get('lat')),lon=Number(u.searchParams.get('lon'));if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error('invalid coordinate');const geom={points:[[lon,lat]],spatialReference:{wkid:4326}},q=new URLSearchParams({geometryType:'esriGeometryMultipoint',geometry:JSON.stringify(geom),f:'json',returnFirstValueOnly:'true',interpolation:'RSP_BilinearInterpolation'}),raw=JSON.parse(await cachedText(BATHY.samples+'?'+q,300000));if(raw.error)throw Error(raw.error.message||'NCEI sample error');const s=raw.samples?.[0],e=num(String(s?.value??s?.attributes?.PixelValue??'').split(',')[0]);return {lat,lon,elevationM:e,depthM:Number.isFinite(e)&&e<0?-e:0,resolutionM:num(s?.resolution),rasterId:s?.rasterId??null,source:BATHY.id,classification:'HISTORICAL/SURVEYED OR COMPILED BOTTOM BASELINE',surveyDate:null,surveyDateStatus:'UNRESOLVED',model:{status:'NOT APPLIED TO DEPTH'}}}
function health(){return {ok:true,version:VERSION,architecture:{terrain:'PERSISTENT_DISK_CACHED_BASELINE',dynamic:'LIVE_AND_MORPHOLOGY_OVERLAYS_ONLY'},terrainCache:CACHE_DIR,checkedAt:new Date().toISOString()}}
const server=http.createServer(async(req,res)=>{try{if(req.method!=='GET')return send(res,405,JSON.stringify({error:'GET only'}));const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health')return send(res,200,JSON.stringify(health()));if(u.pathname==='/api/conditions')return send(res,200,JSON.stringify(await conditions()));if(u.pathname.startsWith('/api/terrain/'))return terrainTile(res,u);if(u.pathname==='/api/identify')return send(res,200,JSON.stringify(await identify(u)));const rel=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1)),full=path.resolve(ROOT,rel);if(!full.startsWith(ROOT+path.sep)&&full!==path.join(ROOT,'index.html'))return send(res,403,'Forbidden','text/plain');if(!fs.existsSync(full)||fs.statSync(full).isDirectory())return send(res,404,'Not found','text/plain');const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,sec(types[path.extname(full)]||'application/octet-stream'));fs.createReadStream(full).pipe(res)}catch(e){send(res,502,JSON.stringify({error:'source unavailable',detail:e.message}))}});
server.listen(PORT,'127.0.0.1',()=>console.log(`BREAKSTATE NJ ${VERSION} → http://localhost:${PORT}`));
