const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const ROOT=__dirname,PORT=Number(process.env.PORT||5173),cache=new Map();
const BEACHES={'Mantoloking':{lat:40.040,lon:-74.049,shore:10},'Bay Head':{lat:40.071,lon:-74.042,shore:8},"Jenkinson's":{lat:40.096,lon:-74.036,shore:8},'Manasquan':{lat:40.108,lon:-74.034,shore:8},'Seaside Heights':{lat:39.943,lon:-74.073,shore:8},'Island Beach SP':{lat:39.840,lon:-74.087,shore:12},'Barnegat Light':{lat:39.755,lon:-74.105,shore:25},'Surf City':{lat:39.658,lon:-74.171,shore:35},'Beach Haven':{lat:39.560,lon:-74.244,shore:42},'Brigantine':{lat:39.410,lon:-74.354,shore:55},'Atlantic City':{lat:39.354,lon:-74.425,shore:62},'Ocean City':{lat:39.277,lon:-74.566,shore:55},'Sea Isle City':{lat:39.153,lon:-74.690,shore:48},'Avalon':{lat:39.095,lon:-74.718,shore:45},'Stone Harbor':{lat:39.050,lon:-74.756,shore:45},'Wildwood':{lat:38.988,lon:-74.817,shore:30}};
const NDBC=['44065','44091','44025'];
const BATHY_SOURCES=[{id:'NOAA DEM',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer/getSamples'},{id:'NOAA DEM all',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer/getSamples'},{id:'NOAA CRM',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/CRM_mosaic/ImageServer/getSamples'},{id:'NOAA BAG',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/bag_bathymetry/ImageServer/getSamples'}];
function sec(type='application/json'){return {'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'geolocation=(), microphone=(), camera=()','Cross-Origin-Resource-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; img-src 'self' data: https://basemap.nationalmap.gov; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' https://unpkg.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"}}
function send(res,s,b,t){res.writeHead(s,sec(t));res.end(b)}
function get(url,ttl=120000,binary=false){return new Promise((resolve,reject)=>{const c=cache.get(url);if(c&&Date.now()-c.t<ttl)return resolve(c.v);const req=https.get(url,{timeout:12000,headers:{'User-Agent':'BREAKSTATE-NJ/56.0 (+local research app)','Accept':'*/*'}},r=>{if(r.statusCode!==200){r.resume();return reject(Error('upstream '+r.statusCode))}const chunks=[];let size=0;r.on('data',x=>{size+=x.length;if(size<=8e6)chunks.push(x)});r.on('end',()=>{const buf=Buffer.concat(chunks),v=binary?buf:buf.toString('utf8');cache.set(url,{t:Date.now(),v});resolve(v)})});req.on('timeout',()=>req.destroy(Error('timeout')));req.on('error',reject)})}
function num(v){v=parseFloat(v);return Number.isFinite(v)&&Math.abs(v)<10000?v:null}
function parseNdbc(txt){const ls=txt.trim().split(/\r?\n/),h=ls[0].replace(/^#/,'').trim().split(/\s+/),v=ls.find((x,i)=>i>1&&x.trim()&&!x.startsWith('#'))?.trim().split(/\s+/);if(!v)throw Error('no observation');const o={};h.forEach((k,i)=>o[k]=v[i]);return {timeUTC:`${o.YY}-${o.MM}-${o.DD} ${o.hh}:${o.mm||'00'}Z`,waveHeightM:num(o.WVHT),periodS:num(o.DPD),waveDir:num(o.MWD),windDir:num(o.WDIR),windMS:num(o.WSPD)}}
function parseAdcp(txt){const lines=txt.split(/\r?\n/).filter(x=>x.trim()&&!x.startsWith('#'));if(!lines.length)return null;const v=lines[0].trim().split(/\s+/),nums=v.map(Number).filter(Number.isFinite);if(nums.length<8)return null;return {direction:nums[nums.length-2],speedCMS:nums[nums.length-1]}}
async function conditions(){const r=await Promise.allSettled(NDBC.map(async station=>{const met=parseNdbc(await get(`https://www.ndbc.noaa.gov/data/realtime2/${station}.txt`));let current=null;try{current=parseAdcp(await get(`https://www.ndbc.noaa.gov/data/realtime2/${station}.adcp`))}catch{}return {station,...met,current}}));return {generatedAt:new Date().toISOString(),buoys:r.filter(x=>x.status==='fulfilled').map(x=>x.value),failures:r.filter(x=>x.status==='rejected').length}}
function dest(lat,lon,bearing,meters){const R=6371000,p1=lat*Math.PI/180,l1=lon*Math.PI/180,b=bearing*Math.PI/180,d=meters/R,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b)),l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return [p2*180/Math.PI,l2*180/Math.PI]}
function grid(b){const offshore=(b.shore+90)%360,along=(b.shore+180)%360,pts=[];for(let a=-6;a<=6;a++)for(let x=10;x<=650;x+=20){const c=dest(b.lat,b.lon,along,a*55),p=dest(c[0],c[1],offshore,x);pts.push({lon:p[1],lat:p[0],transect:a,distanceM:x})}return pts}
async function sampleChunk(source,chunk){const geom={points:chunk.map(p=>[p.lon,p.lat]),spatialReference:{wkid:4326}},q=new URLSearchParams({geometryType:'esriGeometryMultipoint',geometry:JSON.stringify(geom),f:'json',returnFirstValueOnly:'true',interpolation:'RSP_BilinearInterpolation'}),raw=JSON.parse(await get(source.url+'?'+q,3600000));if(raw.error)throw Error(raw.error.message||source.id+' error');return (raw.samples||[]).map((s,i)=>({...chunk[i],elevationM:num(String(s.value??s.attributes?.PixelValue??'').split(',')[0]),resolutionM:num(s.resolution),rasterId:s.rasterId})).filter(s=>Number.isFinite(s.elevationM)&&s.elevationM<3&&s.elevationM>-100)}
async function sampleSource(source,pts){let out=[];for(let i=0;i<pts.length;i+=18){try{out.push(...await sampleChunk(source,pts.slice(i,i+18)))}catch{}}return out}
async function bathy(name){const b=BEACHES[name];if(!b)throw Error('beach not allowed');const pts=grid(b);let best=[],used=null;for(const source of BATHY_SOURCES){const s=await sampleSource(source,pts);if(s.length>best.length){best=s;used=source.id}if(s.length/pts.length>.72)break}if(!best.length)throw Error('No NOAA bathymetric samples returned');return {beach:name,center:b,source:used,sampledAt:new Date().toISOString(),samples:best,requested:pts.length,coverage:best.length/pts.length}}
function tileProxy(req,res,u){const z=Number(u.pathname.split('/')[3]),y=Number(u.pathname.split('/')[4]),x=Number(u.pathname.split('/')[5]);if(![z,y,x].every(Number.isInteger)||z<0||z>16||x<0||y<0)return send(res,400,'bad tile','text/plain');const url=`https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/${z}/${y}/${x}`;get(url,86400000,true).then(buf=>{res.writeHead(200,{...sec('image/png'),'Cache-Control':'public, max-age=86400'});res.end(buf)}).catch(()=>send(res,502,'tile unavailable','text/plain'))}
const server=http.createServer(async(req,res)=>{try{if(req.method!=='GET')return send(res,405,JSON.stringify({error:'GET only'}));const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health')return send(res,200,JSON.stringify({ok:true,version:'56.0.0'}));if(u.pathname==='/api/conditions')return send(res,200,JSON.stringify(await conditions()));if(u.pathname==='/api/bathy')return send(res,200,JSON.stringify(await bathy(u.searchParams.get('beach')||'Bay Head')));if(u.pathname.startsWith('/api/tile/'))return tileProxy(req,res,u);let rel=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1)),full=path.resolve(ROOT,rel);if(!full.startsWith(ROOT+path.sep)&&full!==path.join(ROOT,'index.html'))return send(res,403,'Forbidden','text/plain');if(!fs.existsSync(full)||fs.statSync(full).isDirectory())return send(res,404,'Not found','text/plain');const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,sec(types[path.extname(full)]||'application/octet-stream'));fs.createReadStream(full).pipe(res)}catch(e){send(res,502,JSON.stringify({error:'source unavailable',detail:e.message}))}});
server.listen(PORT,'127.0.0.1',()=>console.log(`BREAKSTATE NJ V56 → http://localhost:${PORT}`));
