const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const ROOT=__dirname,PORT=Number(process.env.PORT||5173),cache=new Map();
const VERSION='56.1.0-audit';
const BEACHES={'Mantoloking':{lat:40.040,lon:-74.049,shore:10},'Bay Head':{lat:40.071,lon:-74.042,shore:8},"Jenkinson's":{lat:40.096,lon:-74.036,shore:8},'Manasquan':{lat:40.108,lon:-74.034,shore:8},'Seaside Heights':{lat:39.943,lon:-74.073,shore:8},'Island Beach SP':{lat:39.840,lon:-74.087,shore:12},'Barnegat Light':{lat:39.755,lon:-74.105,shore:25},'Surf City':{lat:39.658,lon:-74.171,shore:35},'Beach Haven':{lat:39.560,lon:-74.244,shore:42},'Brigantine':{lat:39.410,lon:-74.354,shore:55},'Atlantic City':{lat:39.354,lon:-74.425,shore:62},'Ocean City':{lat:39.277,lon:-74.566,shore:55},'Sea Isle City':{lat:39.153,lon:-74.690,shore:48},'Avalon':{lat:39.095,lon:-74.718,shore:45},'Stone Harbor':{lat:39.050,lon:-74.756,shore:45},'Wildwood':{lat:38.988,lon:-74.817,shore:30}};
const NDBC=['44065','44091','44025'];
const BATHY_SOURCES=[
{id:'NOAA NCEI DEM Global Mosaic',kind:'SURVEY/MOSAIC BASELINE',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer/getSamples',service:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer'},
{id:'NOAA NCEI DEM All',kind:'SURVEY/MOSAIC BASELINE',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer/getSamples',service:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer'},
{id:'NOAA NCEI Coastal Relief Model',kind:'MODELED/COMPILED BASELINE',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/CRM_mosaic/ImageServer/getSamples',service:'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/CRM_mosaic/ImageServer'},
{id:'NOAA NCEI BAG Bathymetry',kind:'SURVEY ARCHIVE BASELINE',url:'https://gis.ngdc.noaa.gov/arcgis/rest/services/bag_bathymetry/ImageServer/getSamples',service:'https://gis.ngdc.noaa.gov/arcgis/rest/services/bag_bathymetry/ImageServer'}];
function sec(type='application/json'){return {'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'geolocation=(), microphone=(), camera=()','Cross-Origin-Resource-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; img-src 'self' data: https://basemap.nationalmap.gov; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' https://unpkg.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"}}
function send(res,s,b,t){res.writeHead(s,sec(t));res.end(b)}
function get(url,ttl=120000,binary=false,timeout=10000){return new Promise((resolve,reject)=>{const c=cache.get(url);if(c&&Date.now()-c.t<ttl)return resolve(c.v);const req=https.get(url,{timeout,headers:{'User-Agent':`BREAKSTATE-NJ/${VERSION} (data provenance audit)`,'Accept':'*/*'}},r=>{if(r.statusCode!==200){r.resume();return reject(Error(`upstream HTTP ${r.statusCode}`))}const chunks=[];let size=0,tooLarge=false;r.on('data',x=>{size+=x.length;if(size>8e6){tooLarge=true;req.destroy(Error('upstream response too large'));return}chunks.push(x)});r.on('end',()=>{if(tooLarge)return;const buf=Buffer.concat(chunks),v=binary?buf:buf.toString('utf8');cache.set(url,{t:Date.now(),v});resolve(v)})});req.on('timeout',()=>req.destroy(Error('upstream timeout')));req.on('error',reject)})}
function num(v){v=parseFloat(v);return Number.isFinite(v)&&Math.abs(v)<10000?v:null}
function obsTime(o){const y=Number(o.YY),m=Number(o.MM)-1,d=Number(o.DD),h=Number(o.hh),mn=Number(o.mm||0);if(![y,m,d,h,mn].every(Number.isFinite))return null;return new Date(Date.UTC(y,m,d,h,mn)).toISOString()}
function parseNdbc(txt){const ls=txt.trim().split(/\r?\n/),h=ls[0].replace(/^#/,'').trim().split(/\s+/),rows=ls.filter((x,i)=>i>1&&x.trim()&&!x.startsWith('#'));for(const row of rows){const v=row.trim().split(/\s+/),o={};h.forEach((k,i)=>o[k]=v[i]);const observedAt=obsTime(o);if(!observedAt)continue;const waveHeightM=num(o.WVHT),periodS=num(o.DPD),waveDir=num(o.MWD),windDir=num(o.WDIR),windMS=num(o.WSPD);if([waveHeightM,periodS,waveDir,windDir,windMS].some(x=>x!==null))return {observedAt,waveHeightM,periodS,waveDir,windDir,windMS};}throw Error('no valid NDBC observation')}
function ageMinutes(iso){const t=Date.parse(iso);return Number.isFinite(t)?Math.max(0,Math.round((Date.now()-t)/60000)):null}
async function conditions(){const settled=await Promise.allSettled(NDBC.map(async station=>{const met=parseNdbc(await get(`https://www.ndbc.noaa.gov/data/realtime2/${station}.txt`,120000));const age=ageMinutes(met.observedAt);return {station,...met,ageMinutes:age,fresh:age!==null&&age<=180,current:null,currentStatus:'NO VALIDATED CURRENT FEED FOR THIS BUOY'}}));const buoys=settled.filter(x=>x.status==='fulfilled').map(x=>x.value);return {generatedAt:new Date().toISOString(),classification:'LIVE OBSERVATIONS',freshnessRuleMinutes:180,buoys,failures:settled.filter(x=>x.status==='rejected').length,notes:['NDBC wave/wind values are observations and retain their observation timestamp.','No .adcp file is assumed: current is unavailable unless a validated current source is explicitly configured.']}}
function dest(lat,lon,bearing,meters){const R=6371000,p1=lat*Math.PI/180,l1=lon*Math.PI/180,b=bearing*Math.PI/180,d=meters/R,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(b)),l2=l1+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return [p2*180/Math.PI,l2*180/Math.PI]}
function grid(b){const offshore=(b.shore+90)%360,along=(b.shore+180)%360,pts=[];for(let a=-6;a<=6;a++)for(let x=10;x<=650;x+=20){const c=dest(b.lat,b.lon,along,a*55),p=dest(c[0],c[1],offshore,x);pts.push({lon:p[1],lat:p[0],transect:a,distanceM:x})}return pts}
async function sampleChunk(source,chunk){const geom={points:chunk.map(p=>[p.lon,p.lat]),spatialReference:{wkid:4326}},q=new URLSearchParams({geometryType:'esriGeometryMultipoint',geometry:JSON.stringify(geom),f:'json',returnFirstValueOnly:'true',interpolation:'RSP_BilinearInterpolation'}),raw=JSON.parse(await get(source.url+'?'+q,3600000,false,12000));if(raw.error)throw Error(raw.error.message||source.id+' error');return (raw.samples||[]).map((s,i)=>({...chunk[i],elevationM:num(String(s.value??s.attributes?.PixelValue??'').split(',')[0]),resolutionM:num(s.resolution),rasterId:s.rasterId})).filter(s=>Number.isFinite(s.elevationM)&&s.elevationM<3&&s.elevationM>-100)}
async function sampleSource(source,pts){let out=[],failedChunks=0;for(let i=0;i<pts.length;i+=18){try{out.push(...await sampleChunk(source,pts.slice(i,i+18)))}catch{failedChunks++}}return {samples:out,failedChunks}}
async function bathy(name){const b=BEACHES[name];if(!b)throw Error('beach not allowed');const pts=grid(b);let best=[],used=null,attempts=[];for(const source of BATHY_SOURCES){const r=await sampleSource(source,pts);attempts.push({source:source.id,returned:r.samples.length,failedChunks:r.failedChunks});if(r.samples.length>best.length){best=r.samples;used=source}if(r.samples.length/pts.length>.72)break}if(!best.length)throw Error('No NOAA/NCEI bathymetric samples returned');return {beach:name,center:b,source:used.id,sourceKind:used.kind,sourceService:used.service,retrievedAt:new Date().toISOString(),surveyDate:null,surveyDateStatus:'NOT RESOLVED BY GETSAMPLES — DO NOT TREAT RETRIEVAL TIME AS SURVEY DATE',classification:'HISTORICAL/SURVEYED OR COMPILED BOTTOM BASELINE',samples:best,requested:pts.length,coverage:best.length/pts.length,attempts}}
async function health(){const checks=[];async function check(name,url){const started=Date.now();try{await get(url,0,false,6000);checks.push({name,ok:true,latencyMs:Date.now()-started})}catch(e){checks.push({name,ok:false,error:e.message,latencyMs:Date.now()-started})}}await Promise.all([check('NDBC 44065','https://www.ndbc.noaa.gov/data/realtime2/44065.txt'),check('NDBC 44091','https://www.ndbc.noaa.gov/data/realtime2/44091.txt'),check('NDBC 44025','https://www.ndbc.noaa.gov/data/realtime2/44025.txt'),check('NOAA NCEI DEM','https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_global_mosaic/ImageServer?f=json'),check('USGS Topo','https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer?f=json')]);return {ok:checks.every(x=>x.ok),version:VERSION,checkedAt:new Date().toISOString(),checks}}
function tileProxy(req,res,u){const z=Number(u.pathname.split('/')[3]),y=Number(u.pathname.split('/')[4]),x=Number(u.pathname.split('/')[5]);if(![z,y,x].every(Number.isInteger)||z<0||z>16||x<0||y<0)return send(res,400,'bad tile','text/plain');const url=`https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/${z}/${y}/${x}`;get(url,86400000,true).then(buf=>{res.writeHead(200,{...sec('image/png'),'Cache-Control':'public, max-age=86400'});res.end(buf)}).catch(()=>send(res,502,'tile unavailable','text/plain'))}
const server=http.createServer(async(req,res)=>{try{if(req.method!=='GET')return send(res,405,JSON.stringify({error:'GET only'}));const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health')return send(res,200,JSON.stringify(await health()));if(u.pathname==='/api/conditions')return send(res,200,JSON.stringify(await conditions()));if(u.pathname==='/api/bathy')return send(res,200,JSON.stringify(await bathy(u.searchParams.get('beach')||'Bay Head')));if(u.pathname.startsWith('/api/tile/'))return tileProxy(req,res,u);let rel=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1)),full=path.resolve(ROOT,rel);if(!full.startsWith(ROOT+path.sep)&&full!==path.join(ROOT,'index.html'))return send(res,403,'Forbidden','text/plain');if(!fs.existsSync(full)||fs.statSync(full).isDirectory())return send(res,404,'Not found','text/plain');const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,sec(types[path.extname(full)]||'application/octet-stream'));fs.createReadStream(full).pipe(res)}catch(e){send(res,502,JSON.stringify({error:'source unavailable',detail:e.message}))}});
server.listen(PORT,'127.0.0.1',()=>console.log(`BREAKSTATE NJ ${VERSION} → http://localhost:${PORT}`));
