const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),app=fs.readFileSync(path.join(root,'src/app.js'),'utf8'),server=fs.readFileSync(path.join(root,'server.js'),'utf8');new vm.Script(app);new vm.Script(server);
assert(server.includes("VERSION='59.0.0-mvp'"));assert(server.includes("terrain:'EPSG3857_PERSISTENT_STATIC_BASELINE'"));assert(server.includes("path.join(ROOT,'.cache','terrain-v59')"));assert(server.includes("bboxSR:'3857'"));assert(server.includes("imageSR:'3857'"));assert(server.includes("rasterFunction:'ColorHillshade2'"));assert(server.includes("max-age=31536000, immutable"));assert(server.includes("model:{status:'NOT APPLIED TO DEPTH'"));assert(app.includes("L.tileLayer('/api/terrain/{z}/{x}/{y}.png'"));assert(app.includes('maxNativeZoom:17'));assert(!app.includes('/api/tile/'));assert(!app.includes('L.imageOverlay'));assert(!app.includes('circleMarker'));assert(!app.includes('maxBounds:'));assert(!app.includes('Math.random'));assert(!server.includes('Math.random'));
const H=20037508.342789244;
function tileBounds(z,x,y){const n=2**z,span=H*2/n,west=-H+x*span,east=west+span,north=H-y*span,south=north-span;return {north,south,west,east,span}}
let seed=523,passed=0;function rnd(){seed=(1664525*seed+1013904223)>>>0;return seed/4294967296}
const modes=['cold-cache','warm-cache','rapid-pan','rapid-zoom','duplicate-request','server-restart','live-data-down','identify-down'];
for(let i=0;i<400;i++){const z=8+Math.floor(rnd()*10),n=2**z,x=Math.floor(rnd()*(n-1)),y=Math.floor(rnd()*(n-1)),b=tileBounds(z,x,y),right=tileBounds(z,x+1,y),below=tileBounds(z,x,y+1),mode=modes[i%modes.length];assert(z>=8&&z<=17);assert(b.north>b.south&&b.east>b.west);assert(Math.abs(b.east-right.west)<1e-7,'horizontal tile seam mismatch');assert(Math.abs(b.south-below.north)<1e-7,'vertical tile seam mismatch');assert(Math.abs((b.east-b.west)-(b.north-b.south))<1e-7,'Web Mercator tile not square');if(mode==='duplicate-request')assert(server.includes('inflight.has(key)'));if(mode==='server-restart')assert(server.includes('fs.existsSync(file)'));if(mode==='live-data-down')assert(app.includes('Static terrain remains usable'));passed++}
console.log(`PASS V59 MVP: ${passed} deterministic scenarios; JS syntax; EPSG:3857 tile projection; horizontal/vertical seam invariants; cache/restart/failure architecture`);
