const beaches=[['Sandy Hook',40.466,-74.003],['Long Branch',40.304,-73.980],['Asbury Park',40.220,-74.000],['Belmar',40.180,-74.010],['Spring Lake',40.151,-74.026],['Manasquan',40.108,-74.034],["Jenkinson's",40.096,-74.036],['Bay Head',40.071,-74.042],['Mantoloking',40.040,-74.049],['Seaside Heights',39.943,-74.073],['Island Beach SP',39.840,-74.087],['Barnegat Light',39.755,-74.105],['Surf City',39.658,-74.171],['Beach Haven',39.560,-74.244],['Brigantine',39.410,-74.354],['Atlantic City',39.354,-74.425],['Ocean City',39.277,-74.566],['Sea Isle City',39.153,-74.690],['Avalon',39.095,-74.718],['Stone Harbor',39.050,-74.756],['Wildwood',38.988,-74.817]];
let conditions=null,seabed=L.layerGroup(),controller=null,loadTimer=null;
const palette=['#24105f','#163b9a','#1269c7','#169fd0','#22c7bd','#49d38d','#82dc5c','#c9df4a','#f4d83e','#f5aa38','#ef6b38','#e73c55','#d31b85'];
document.getElementById('app').innerHTML=`<header><div><b>BREAKSTATE <i>NJ</i></b><span>Nearshore Intelligence · V57.1 Source Geometry</span></div><em id="status">CONNECTING</em></header><div class="shell"><aside><h3>JUMP TO BEACH</h3><select id="beach"><option value="">Scroll the coast freely</option>${beaches.map(b=>`<option>${b[0]}</option>`).join('')}</select><div class="tabs"><button class="active" data-base="topo">TOPO</button><button data-base="off">TERRAIN ONLY</button></div><div id="live" class="card">Loading timestamped NOAA observations…</div><h3>DISPLAY</h3><label class="check"><input id="seabedToggle" type="checkbox" checked> Bathymetric terrain surface</label><h3>WHAT CHANGED</h3><p class="small">No hand-drawn NJ coastline and no beach transect origins are used to position depths. The visible map is sampled as a geographic grid. The water/land edge is derived from the same returned elevation surface, so inlets and shoreline bends are not forced through straight interpolated beach points. Color between source nodes is display interpolation only.</p><div id="source" class="source"></div></aside><main><div id="map"></div><div class="legend"><b>SEAFLOOR DEPTH · SHALLOW → DEEP</b><div class="gradient"></div><div class="ticks"><span>deep</span><span>8m</span><span>6m</span><span>4m</span><span>2m</span><span>shore</span></div></div><section id="readout"><div class="loading">Loading elevation surface…</div></section></main></div>`;
const map=L.map('map',{preferCanvas:true,zoomControl:true,maxBounds:[[38.90,-75.15],[40.55,-73.55]],maxBoundsViscosity:.7}).setView([40.071,-74.025],14);
const base=L.tileLayer('/api/tile/{z}/{y}/{x}',{maxZoom:16,attribution:'USGS The National Map'}).addTo(map);seabed.addTo(map);
const statusEl=document.getElementById('status'),sourceEl=document.getElementById('source'),readoutEl=document.getElementById('readout'),liveEl=document.getElementById('live');
function rgb(hex){return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]}
function depthRGB(z){const d=Math.max(0,Math.min(12,-z)),u=(12-d)/12*(palette.length-1),i=Math.floor(u),f=u-i,a=rgb(palette[Math.max(0,Math.min(palette.length-1,i))]),b=rgb(palette[Math.max(0,Math.min(palette.length-1,i+1))]);return a.map((v,k)=>Math.round(v+(b[k]-v)*f))}
function bilinear(z00,z10,z11,z01,u,v){return z00*(1-u)*(1-v)+z10*u*(1-v)+z11*u*v+z01*(1-u)*v}
function drawSurface(d){const by=new Map(d.samples.map(s=>[`${s.row}:${s.col}`,s])),N=d.rows,M=d.cols;for(let row=0;row<N-1;row++)for(let col=0;col<M-1;col++){const a=by.get(`${row}:${col}`),b=by.get(`${row}:${col+1}`),c=by.get(`${row+1}:${col+1}`),e=by.get(`${row+1}:${col}`);if(!a||!b||!c||!e)continue;const z=[a.elevationM,b.elevationM,c.elevationM,e.elevationM];if(Math.min(...z)>.25)continue;const W=24,H=24,cv=document.createElement('canvas');cv.width=W;cv.height=H;const ctx=cv.getContext('2d'),im=ctx.createImageData(W,H);for(let y=0;y<H;y++)for(let x=0;x<W;x++){const u=x/(W-1),v=y/(H-1),q=bilinear(z[0],z[1],z[2],z[3],u,v),k=(y*W+x)*4;if(q<=.25){const co=depthRGB(Math.min(0,q));im.data[k]=co[0];im.data[k+1]=co[1];im.data[k+2]=co[2];im.data[k+3]=222}else im.data[k+3]=0}ctx.putImageData(im,0,0);L.imageOverlay(cv.toDataURL('image/png'),[[e.lat,a.lon],[a.lat,b.lon]],{opacity:.92,interactive:false}).addTo(seabed)}}
async function loadVisible(){if(map.getZoom()<12){statusEl.textContent='ZOOM IN FOR BATHYMETRY';return}const b=map.getBounds(),north=Math.min(40.55,b.getNorth()+.004),south=Math.max(38.90,b.getSouth()-.004),west=Math.max(-75.15,b.getWest()-.004),east=Math.min(-73.55,b.getEast()+.004);if(north-south>.13||east-west>.13){statusEl.textContent='ZOOM IN FOR DETAIL';return}if(controller)controller.abort();controller=new AbortController();statusEl.textContent='LOADING SOURCE GEOMETRY';try{const q=new URLSearchParams({north:north.toFixed(6),south:south.toFixed(6),west:west.toFixed(6),east:east.toFixed(6)}),r=await fetch('/api/surface?'+q,{cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok||!d.samples?.length)throw Error(d.detail||'No samples');seabed.clearLayers();drawSurface(d);const dep=d.samples.filter(x=>x.elevationM<=.25).map(x=>Math.max(0,-x.elevationM));sourceEl.innerHTML=`<b>${d.source}</b><span>${d.waterSamples} water / ${d.samples.length} returned grid nodes · ${Math.round(d.coverage*100)}% grid coverage</span><span>${d.geometry}</span><span>Survey date unresolved; this remains historical/compiled baseline data.</span>`;readoutEl.innerHTML=`<div><label>VISIBLE UNDERWATER TERRAIN · BASELINE</label><strong>${dep.length?Math.min(...dep).toFixed(1)+'–'+Math.max(...dep).toFixed(1)+' m':'No water depths'}</strong><span>Geographic source grid; no synthetic coastline or transect geometry · ${d.failedChunks} failed source chunks</span></div><div><label>SHORE / INLET EDGE</label><strong>SOURCE-DERIVED</strong><span>Display boundary follows the zero-elevation transition in the returned elevation grid instead of the old interpolated beach-point coastline.</span></div><div><label>CURRENT MORPHOLOGY</label><strong>NOT YET APPLIED</strong><span>No unvalidated sand movement has been added to measured/compiled baseline depths.</span></div>`;statusEl.textContent='BATHYMETRIC TERRAIN · BASELINE'}catch(e){if(e.name==='AbortError')return;statusEl.textContent='SOURCE ERROR';readoutEl.innerHTML=`<div class="error"><b>SEAFLOOR UNAVAILABLE</b><span>${e.message}. No synthetic depth substituted.</span></div>`}}
function scheduleLoad(){clearTimeout(loadTimer);loadTimer=setTimeout(loadVisible,350)}
async function loadLive(){try{const r=await fetch('/api/conditions',{cache:'no-store'});conditions=await r.json();liveEl.innerHTML=conditions.buoys.map(x=>`<div><b>NOAA NDBC ${x.station} · ${x.fresh?'LIVE':'STALE'}</b><strong>${x.waveHeightM!=null?(x.waveHeightM*3.28084).toFixed(1)+' ft':'wave unavailable'}${x.periodS!=null?' @ '+x.periodS+'s':''}</strong><span>${x.waveDir??'—'}° · ${x.ageMinutes??'—'} min old</span></div>`).join('')||'<span>No NDBC observations returned.</span>'}catch{conditions=null;liveEl.innerHTML='<span>Live NOAA observations unavailable.</span>'}scheduleLoad()}
document.getElementById('beach').onchange=e=>{const b=beaches.find(x=>x[0]===e.target.value);if(b)map.setView([b[1],b[2]+.012],14)};document.getElementById('seabedToggle').onchange=e=>e.target.checked?map.addLayer(seabed):map.removeLayer(seabed);document.querySelectorAll('[data-base]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-base]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');btn.dataset.base==='topo'?map.addLayer(base):map.removeLayer(base)});map.on('moveend zoomend',scheduleLoad);loadLive();setInterval(loadLive,180000);
